#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication blockMesh

# runApplication snappyHexMesh -overwrite 

# runApplication extrudeMesh

# runApplication createPatch -overwrite

runApplication topoSet
runApplication collapseEdges -overwrite

runApplication splitMeshRegions -cellZones -overwrite


restore0Dir 
rm -rf constant/polyMesh

runApplication setExprFields -region fluid
runApplication initAlphaField -region fluid
runApplication setFields -region fluid

touch singlephase.foam

# runApplication decomposePar -allRegions
# runParallel $(getApplication)
# runApplication reconstructPar -allRegions

runApplication $(getApplication)

#------------------------------------------------------------------------------
