#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication blockMesh
runApplication snappyHexMesh -overwrite 

runApplication extrudeMesh 

runApplication createPatch -overwrite
runApplication renumberMesh -overwrite
runApplication topoSet

runApplication splitMeshRegions -cellZones -overwrite
restore0Dir 
rm -rf constant/polyMesh
runApplication initAlphaField -region fluid
runApplication setFields -region fluid
runApplication setExprFields -region fluid

#------------------------------------------------------------------------------
